name: Challenge 5

on:
  push:
    branches: ["main","master"]

jobs:
  experiment:
    name: Training model in dev environment
    runs-on: ubuntu-latest
    environment: development
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install Azure CLI
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
    - name: Install Azure ML Extensions
      run: |
        az extension add --name ml --yes
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Set Azure subscription
      run: |
        az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - name: Set Azure ML defaults
      run: |
        az configure --defaults group=rg-lvela-training workspace=aml-lvela-training
    - name: Run Azure ML job (development)
      run: |
        az ml job create --file src/job.yml --stream

  production:
    name: Train model in production
    runs-on: ubuntu-latest
    needs: experiment
    environment: production
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install Azure CLI
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
    - name: Install Azure ML extension
      run: |
        az extension add --name ml --yes
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Set Azure ML defaults
      run: |
        az configure --defaults group=rg-lvela-training workspace=aml-lvela-training
    - name: Run Azure ML job (production)
      run: |
        az ml job create --file src/job.yml --set inputs.training_data.path=azureml:diabetes-prod-folder@latest --stream